### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by flamendless** [tbastos/vim-lua#11]
Hey, how can i highlight the self keyword? thanks

**Comment by flamendless** [comment]
Also, how to enable self to be highlighted with dot(.) And also if is inside tables and functions

**Comment by idbrii** [comment]
> Hey, how can i highlight the self keyword? thanks

[self is linked to luaBuiltIn](https://github.com/tbastos/vim-lua/blob/master/syntax/lua.vim#L112).
[luaBuiltIn is linked to Special](https://github.com/tbastos/vim-lua/blob/master/syntax/lua.vim#L203).

You can try a colorscheme that sets Special or define a colour for it yourself in your vimrc (after you invoke `:colorscheme`):

    hi Special guifg=navajowhite

> Also, how to enable self to be highlighted with dot(.) And also if is inside tables and functions

Works for me?
