### ISSUE TITLE
Weird function colour

### ISSUE THREAD

**Issue by Atcold** [tbastos/vim-lua#9]
Before it was like this.

![image](https://user-images.githubusercontent.com/2119355/32123471-46de6d00-bb32-11e7-8573-9f937750e5f1.png)

Now it looks like this.

![image](https://user-images.githubusercontent.com/2119355/32123488-5c51a29c-bb32-11e7-93ae-d75ef5f9f72b.png)

Can I have some orange back? Perhaps for the function calls, instead of all this green?
Also, now `local` and `function` share the same colour. Can I get `function` to be green again?

**Comment by tbastos** [comment]
Have you tried other color schemes? Results will vary depending on the color scheme.

vim(-lua)'s syntax file only maps tokens to "highlight groups", not to a color. Your color scheme is then responsible for mapping a "highlight group" to a color. You can fine-tune your colors by writing custom highlight rules to complement your color scheme's defaults. To understand how tokens in your Lua code are mapped to highlight groups, you can use one of the techniques described here: http://vim.wikia.com/wiki/Identify_the_syntax_highlighting_group_used_at_the_cursor

**Comment by Atcold** [comment]
Exactly, `luaFunction` was mapped by default to `Function`.
Now you've changed it to `Structure`. Changing it back to `Function` does not restore the previous colour.
That's why I opened this issue. I'm not sure how to deal with your plugin.

**Comment by Atcold** [comment]
OK, my bad... A normal function call was labelled as `luaFunc`, and not `luaFunction`... which was mapped to `Identifier`, which is mapped to `ctermfg=208` in my colour scheme, which is the orange I was looking for.

![image](https://user-images.githubusercontent.com/2119355/32149069-c54cb6ac-bcd5-11e7-8c94-a435cfe2178a.png)

**Comment by Atcold** [comment]
Now I have a different question. Originally a library function call was mapped to `Identifier`, and now I have it pointing to `PreProc`, which is the green I don't like.
How do I override your change? I don't want to necessarily change my colour scheme because the mapping has changed (which could affect other syntaxes).
How do you deal with this situation?

**Comment by Atcold** [comment]
OK, just added this to my `$VIMRC`:
```vim
hi def link luaSpecialValue Identifier
```
which is the answer to my initial question.
Now the issue can be closed.
